name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4

    # https://github.com/marketplace/actions/setup-python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install deps and execute
      run: |
        python -m pip install --upgrade pip
        python -m pip install datetime
    - run: |
        python generate_sitemap.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        commit-message: 'Autonomous sitemap update'
        committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
        author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
        signoff: false
        title: 'Update sitemap'
        body: |
            Automated PR to update sitemap
        labels: |
            sitemap
        assignees: jhpohovey
        reviewers: jhpohovey
        draft: false
        branch: update-sitemap
        delete-branch: false