name: Generate Sitemap

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4

    # https://github.com/marketplace/actions/setup-python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install deps and execute
      run: |
        python -m pip install --upgrade pip
        python -m pip install datetime
    - run: |
        python generate_sitemap.py

    - name: Create Pull Request
      id: make-pr
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.WEBSITE_TOKEN }}
        commit-message: 'Autonomous sitemap update'
        committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        signoff: false
        title: 'Update sitemap'
        body: |
            Automated PR to update sitemap
        labels: |
            sitemap
        draft: false
        branch: update-sitemap
        delete-branch: false

    - name: Sleep to allow Pull Request to settle, get a defined status
      uses: whatnick/wait-action@master
      with:
        time: "5s"
      if: steps.make-pr.outputs.pull-request-number != ''

    - name: Merge Version Bump Pull Request
      uses: juliangruber/merge-pull-request-action@v1
      with:
        github-token: ${{ secrets.WEBSITE_TOKEN }}
        number: ${{ steps.make-pr.outputs.pull-request-number }}
        method: "merge"
      if: steps.make-pr.outputs.pull-request-number != ''




