name: Generate Sitemap

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4

    # https://github.com/marketplace/actions/setup-python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Install deps and execute
      run: |
        python -m pip install --upgrade pip
        python -m pip install datetime
    - run: |
        python generate_sitemap.py

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.WEBSITE_TOKEN}}
        commit-message: 'Autonomous sitemap update'
        committer: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
        author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
        signoff: false
        title: 'Update sitemap'
        body: |
            Automated PR to update sitemap
        labels: |
            sitemap
            automerge
        draft: false
        branch: update-sitemap
        delete-branch: false

    - name: Merge PR Automatically
      id: automerge
      uses: pascalgn/automerge-action@v0.16.3
      env:
        MERGE_LABELS: 'automerge'
        MERGE_METHOD: 'merge'
        MERGE_RETRIES: 1
        MERGE_RETRY_SLEEP: 30000
        MERGE_COMMIT_MESSAGE: "pull-request-title-and-description"
        MERGE_DELETE_BRANCH: true
        MERGE_READY_STATE: "clean,unknown,has_hooks" # but not unstable
        GITHUB_TOKEN: "${{ secrets.WEBSITE_TOKEN }}"
        LOG: "DEBUG"
        UPDATE_LABELS: "automerge"
        UPDATE_METHOD: "merge"
        UPDATE_RETRIES: 1
        UPDATE_RETRY_SLEEP: 30000

    # - name: feedback
    #   if: ${{ steps.automerge.outputs.mergeResult == 'merged' }}
    #   run: |
    #     echo "Pull request ${{ steps.automerge.outputs.pullRequestNumber }} merged!"
